export const POST_REQUEST = 'POST_REQUEST'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_REMOVE = 'POST_REMOVE'
export const POST_READ_MORE = 'POST_READ_MORE'
export const LOGIN = 'LOGIN'
export const LOG_OUT = 'LOG_OUT'